#ifndef PERFORMANCE_ANALYSIS_OF_GRAPH_ALGORITHMS_IN_DIFFERENT_GRAPH_REPRESENTATIONS_GENERATERANDOMGRAPHFILE_H
#define PERFORMANCE_ANALYSIS_OF_GRAPH_ALGORITHMS_IN_DIFFERENT_GRAPH_REPRESENTATIONS_GENERATERANDOMGRAPHFILE_H

#include <string>

using namespace std;

class GenerateRandomGraphFile {
public:
    void generateGraphFile(const string& filename, int vertices, double density);
};

#endif //PERFORMANCE_ANALYSIS_OF_GRAPH_ALGORITHMS_IN_DIFFERENT_GRAPH_REPRESENTATIONS_GENERATERANDOMGRAPHFILE_H
