#ifndef PERFORMANCE_ANALYSIS_OF_GRAPH_ALGORITHMS_IN_DIFFERENT_GRAPH_REPRESENTATIONS_PRIMADJACENCYLIST_H
#define PERFORMANCE_ANALYSIS_OF_GRAPH_ALGORITHMS_IN_DIFFERENT_GRAPH_REPRESENTATIONS_PRIMADJACENCYLIST_H

#include "../Headers/AdjacencyList.h"

class PrimAdjacencyList {
public:
    static void run(AdjacencyList* graph, int startVertex, int endVertex);
};

#endif //PERFORMANCE_ANALYSIS_OF_GRAPH_ALGORITHMS_IN_DIFFERENT_GRAPH_REPRESENTATIONS_PRIMADJACENCYLIST_H
