#ifndef PERFORMANCE_ANALYSIS_OF_GRAPH_ALGORITHMS_IN_DIFFERENT_GRAPH_REPRESENTATIONS_PRIMINCIDENCEMATRIX_H
#define PERFORMANCE_ANALYSIS_OF_GRAPH_ALGORITHMS_IN_DIFFERENT_GRAPH_REPRESENTATIONS_PRIMINCIDENCEMATRIX_H

#include "../Headers/IncidentMatrix.h"

class PrimIncidenceMatrix {
public:
    static void run(IncidentMatrix* graph, int startVertex, int endVertex); // Added endVertex parameter
};

#endif //PERFORMANCE_ANALYSIS_OF_GRAPH_ALGORITHMS_IN_DIFFERENT_GRAPH_REPRESENTATIONS_PRIMINCIDENCEMATRIX_H